---
info:
  _postman_id: 14715950-9d3a-4530-9449-0e614280547d
  name: Tugas-besar-pemograman
  schema: https://schema.getpostman.com/json/collection/v2.1.0/collection.json
  _exporter_id: '33966215'
item:
- name: Login
  request:
    auth:
      type: bearer
    method: POST
    header: []
    body:
      mode: raw
      raw: "{\r\n    \"username\" : \"Banban\",\r\n    \"password\" : \"12345\"\r\n}"
      options:
        raw:
          language: json
    url:
      raw: http://localhost:8080/login
      protocol: http
      host:
      - localhost
      port: '8080'
      path:
      - login
  response: []
- name: Regis
  request:
    method: POST
    header: []
    body:
      mode: raw
      raw: "{\r\n    \"email\" :  \"danymr@gmail.com\",\r\n    \"username\" : \"Budiono\",\r\n
        \   \"password\" : \"12345\"\r\n}"
      options:
        raw:
          language: json
    url:
      raw: http://localhost:8080/regis
      protocol: http
      host:
      - localhost
      port: '8080'
      path:
      - regis
  response: []
- name: Get All pakaian
  protocolProfileBehavior:
    disableBodyPruning: true
  request:
    method: GET
    header: []
    body:
      mode: raw
      raw: ''
      options:
        raw:
          language: json
    url:
      raw: http://localhost:8080/pakaian
      protocol: http
      host:
      - localhost
      port: '8080'
      path:
      - pakaian
  response: []
- name: Post Pakaian
  request:
    auth:
      type: bearer
      bearer:
      - key: token
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJhbmJhbiIsImV4cCI6MTcxOTcyNDc4N30.gh1JFNyhZ8wiQq6sdtWW4HvQ2QV3dTMOXH00OSCFhLc
        type: string
    method: POST
    header: []
    body:
      mode: raw
      raw: "{\r\n    \"namapakaian\": \"Baju Berbulu\",\r\n    \"deskripsi\": \"Bagus
        untuk musim dingin\",\r\n    \"ukuran\": \"XL\",\r\n    \"stok\": 25,\r\n
        \   \"hargapakaian\": 500000\r\n}\r\n"
      options:
        raw:
          language: json
    url:
      raw: http://localhost:8080/pakaian
      protocol: http
      host:
      - localhost
      port: '8080'
      path:
      - pakaian
  response: []
- name: Update Pakaian
  request:
    auth:
      type: bearer
      bearer:
      - key: token
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJhbmJhbiIsImV4cCI6MTcxOTcyNDc4N30.gh1JFNyhZ8wiQq6sdtWW4HvQ2QV3dTMOXH00OSCFhLc
        type: string
    method: PUT
    header: []
    body:
      mode: raw
      raw: "{\r\n    \"namapakaian\": \"Baju Berbulu Rusa\",\r\n    \"deskripsi\":
        \"Bagus untuk musim yang sangat dingin\",\r\n    \"ukuran\": \"XXL\",\r\n
        \   \"stok\": 254,\r\n    \"hargapakaian\": 50100\r\n}\r\n"
      options:
        raw:
          language: json
    url:
      raw: http://localhost:8080/pakaian/3
      protocol: http
      host:
      - localhost
      port: '8080'
      path:
      - pakaian
      - '3'
  response: []
- name: Delete Pakaian
  request:
    auth:
      type: bearer
      bearer:
      - key: token
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJhbmJhbiIsImV4cCI6MTcxOTcyNDc4N30.gh1JFNyhZ8wiQq6sdtWW4HvQ2QV3dTMOXH00OSCFhLc
        type: string
    method: DELETE
    header: []
    url:
      raw: http://localhost:8080/pakaian/5
      protocol: http
      host:
      - localhost
      port: '8080'
      path:
      - pakaian
      - '5'
  response: []
- name: Get Pembeli
  protocolProfileBehavior:
    disableBodyPruning: true
  request:
    method: GET
    header: []
    body:
      mode: raw
      raw: ''
      options:
        raw:
          language: json
    url:
      raw: http://localhost:8080/pembeli
      protocol: http
      host:
      - localhost
      port: '8080'
      path:
      - pembeli
  response: []
- name: Post Pembeli
  request:
    auth:
      type: bearer
      bearer:
      - key: token
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJhbmJhbiIsImV4cCI6MTcxOTcyNDc4N30.gh1JFNyhZ8wiQq6sdtWW4HvQ2QV3dTMOXH00OSCFhLc
        type: string
    method: POST
    header: []
    body:
      mode: raw
      raw: "{\r\n  \"nama\": \"Jane Doe\",\r\n  \"email\": \"jane.doe@example.com\",\r\n
        \ \"jumlahpembelian\": 50\r\n}\r\n"
      options:
        raw:
          language: json
    url:
      raw: http://localhost:8080/pembeli
      protocol: http
      host:
      - localhost
      port: '8080'
      path:
      - pembeli
  response: []
- name: Update Pembeli
  request:
    auth:
      type: bearer
      bearer:
      - key: token
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJhbmJhbiIsImV4cCI6MTcxOTcyNDc4N30.gh1JFNyhZ8wiQq6sdtWW4HvQ2QV3dTMOXH00OSCFhLc
        type: string
    method: PUT
    header: []
    body:
      mode: raw
      raw: "{\r\n  \"nama\": \"jodi didodo\",\r\n  \"email\": \"joko.doe@example.com\",\r\n
        \ \"jumlahpembelian\": 100\r\n}\r\n"
      options:
        raw:
          language: json
    url:
      raw: http://localhost:8080/pembeli/4
      protocol: http
      host:
      - localhost
      port: '8080'
      path:
      - pembeli
      - '4'
  response: []
- name: Delete Pembeli
  request:
    auth:
      type: bearer
      bearer:
      - key: token
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJhbmJhbiIsImV4cCI6MTcxOTcyNDc4N30.gh1JFNyhZ8wiQq6sdtWW4HvQ2QV3dTMOXH00OSCFhLc
        type: string
    method: DELETE
    header: []
    body:
      mode: raw
      raw: ''
      options:
        raw:
          language: json
    url:
      raw: http://localhost:8080/pembeli/4
      protocol: http
      host:
      - localhost
      port: '8080'
      path:
      - pembeli
      - '4'
  response: []
