openapi: 3.0.0
info:
  title: "Tugas Besar Pemograman"
  version: "1.0.0"
paths:
  /login:
    post:
      summary: "Login"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              example:
                username: "Banban"
                password: "12345"
      responses:
        '200':
          description: "Successful login"
  /regis:
    post:
      summary: "Register"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                username:
                  type: string
                password:
                  type: string
              example:
                email: "danymr@gmail.com"
                username: "Budiono"
                password: "12345"
      responses:
        '200':
          description: "Successful registration"
  /pakaian:
    get:
      summary: "Get All Pakaian"
      responses:
        '200':
          description: "Successful operation"
    post:
      summary: "Post Pakaian"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                namapakaian:
                  type: string
                deskripsi:
                  type: string
                ukuran:
                  type: string
                stok:
                  type: integer
                hargapakaian:
                  type: integer
              example:
                namapakaian: "Baju Berbulu"
                deskripsi: "Bagus untuk musim dingin"
                ukuran: "XL"
                stok: 25
                hargapakaian: 500000
      responses:
        '200':
          description: "Successful operation"
  /pakaian/{id}:
    put:
      summary: "Update Pakaian"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                namapakaian:
                  type: string
                deskripsi:
                  type: string
                ukuran:
                  type: string
                stok:
                  type: integer
                hargapakaian:
                  type: integer
              example:
                namapakaian: "Baju Berbulu Rusa"
                deskripsi: "Bagus untuk musim yang sangat dingin"
                ukuran: "XXL"
                stok: 254
                hargapakaian: 50100
      responses:
        '200':
          description: "Successful operation"
    delete:
      summary: "Delete Pakaian"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "Successful operation"
  /pembeli:
    get:
      summary: "Get Pembeli"
      responses:
        '200':
          description: "Successful operation"
    post:
      summary: "Post Pembeli"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nama:
                  type: string
                email:
                  type: string
                jumlahpembelian:
                  type: integer
              example:
                nama: "Jane Doe"
                email: "jane.doe@example.com"
                jumlahpembelian: 50
      responses:
        '200':
          description: "Successful operation"
  /pembeli/{id}:
    put:
      summary: "Update Pembeli"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nama:
                  type: string
                email:
                  type: string
                jumlahpembelian:
                  type: integer
              example:
                nama: "jodi didodo"
                email: "joko.doe@example.com"
                jumlahpembelian: 100
      responses:
        '200':
          description: "Successful operation"
    delete:
      summary: "Delete Pembeli"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "Successful operation"
